# Generated by Django 5.2.2 on 2025-06-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
