# Generated by Django 5.2.2 on 2025-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanPanel', '0002_lead_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
