# Generated by Django 5.2.2 on 2025-06-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanPanel', '0004_category_alter_lead_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interest',
            field=models.TextField(null=True),
        ),
    ]
